### ISSUE TITLE
iOS compilation fail

### ISSUE THREAD

**Issue by oguilb** [mattermost/react-native-network-client#102]
HI,

I have a compilation error.  clientCredential: clientCredential parameter not defined (WebSocketManager.swift) 

```swift
 let webSocket = WebSocket(request: request, certPinner: certPinner, clientCredential: clientCredential, compressionHandler: compressionHandler)
```
Have you a solution? is required for me.

Regards

**Comment by enahum** [comment]
Can you provide more details? The library seems to compile just fine in our project.

Perhaps if you provide more information about the compilation error and implementation details that can allow us to help you a bit better

**Comment by oguilb** [comment]
I use:
    - RN 0.66.4
    - Pods:

          - Alamofire (~> 5.4)
          - React-Core
          - Starscream (~> 4.0.4)
          - SwiftyJSON (~> 5.0)

When I build my project for iOS, I have this error:

```
The following build commands failed:
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'react-native-network-client' from project 'Pods')
        CompileSwift normal x86_64 /Users/xxxxx/node_modules/@mattermost/react-native-network-client/ios/WebSocketManager.swift (in target 'react-native-network-client' from project 'Pods')
```
With XCode editor, the error is identified at line 72 of WebSocketManager.swift with:

```
Extra argument 'clientCredential' in call
```

**Comment by oguilb** [comment]
Ok, I have append this

```
pod 'Starscream', :git => 'https://github.com/mattermost/Starscream.git', :commit => '1b4b93708fb63d2665625a11e57461772a65364a'
```

In my Podfile and it's work. 
Sorry for the inconvenience. If I had read the doc :-(
